id = gfn
name = GeForce NOW Stable Fix
mainURL = https://play.geforcenow.com
deeplink = play.geforcenow.com
icon = gfn.png
scripts = inject.js

allowSubdomains = true
requireDoubleBackToExit = true

enableExternalLinks = true
openExternalLinksInBrowser = false
confirmOpenInBrowser = false

MediaPlaybackRequiresUserGesture = false
DebugWebView = false
